services:
  postgres:
    build:
      context: ..
      dockerfile: testEnv/postgres.dockerfile
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
